AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  template apps

  Runs tests for the apps in this repository. See README.md for how to start

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  example:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: template_function/
      Handler: app.docker_entry_point.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: test1
          LOG_LEVEL: DEBUG # One of [DEBUG|INFO|WARNING|CRITICAL]
          TZ: "Europe/London"
          APPNAME: template
          AWS_REGION: eu-west-2
          AWS_DEFAULT_REGION: eu-west-2
          LOCAL_DEV: "True"
 